#pragma once

// System.Reflection.ParameterModifier
struct ParameterModifier_t1348;
struct ParameterModifier_t1348_marshaled;

void ParameterModifier_t1348_marshal(const ParameterModifier_t1348& unmarshaled, ParameterModifier_t1348_marshaled& marshaled);
void ParameterModifier_t1348_marshal_back(const ParameterModifier_t1348_marshaled& marshaled, ParameterModifier_t1348& unmarshaled);
void ParameterModifier_t1348_marshal_cleanup(ParameterModifier_t1348_marshaled& marshaled);
